name: master
on:
  push:
    branches:
        - master

jobs:
  master-job:
    name: master
    runs-on: ubuntu-latest
    env:
      region : europe-west1
      ENVIRONMENT: staging
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: actions/setup-go@v1.1.2
      with:
        stable: 'true'
        go-version: '1.13.7'
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
      with:
       service_account_email: ${{ secrets.GCP_SA_EMAIL_STAGING }}
       service_account_key: ${{ secrets.GCP_SA_SECRET_STAGING }}
       export_default_credentials: true
    - name: gcloud Set up
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID_STAGING }}
    - name: Run Unit Tests
      run: make test
    - name: Prepare app.yaml
      run: ./scripts/prepare_app-yaml.sh "${{ env.ENVIRONMENT }}"
    - name: Promote Application in Staging
      run: make promote serviceaccount=${{ secrets.GCP_SA_EMAIL_STAGING }}
    - name: Run Integration Tests
      run: make integration
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2.1.3
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}